// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geo-me.proto

package au.com.ausstaker.snet.server;

public interface GeolocationResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GeolocationResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double residual = 1;</code>
   * @return The residual.
   */
  double getResidual();

  /**
   * <code>double residual_rk = 2;</code>
   * @return The residualRk.
   */
  double getResidualRk();

  /**
   * <code>double lat = 3;</code>
   * @return The lat.
   */
  double getLat();

  /**
   * <code>double lon = 4;</code>
   * @return The lon.
   */
  double getLon();

  /**
   * <code>double elp_long = 5;</code>
   * @return The elpLong.
   */
  double getElpLong();

  /**
   * <code>double elp_short = 6;</code>
   * @return The elpShort.
   */
  double getElpShort();

  /**
   * <code>double elp_rot = 7;</code>
   * @return The elpRot.
   */
  double getElpRot();

  /**
   * <code>string kml_output = 8;</code>
   * @return The kmlOutput.
   */
  java.lang.String getKmlOutput();
  /**
   * <code>string kml_output = 8;</code>
   * @return The bytes for kmlOutput.
   */
  com.google.protobuf.ByteString
      getKmlOutputBytes();

  /**
   * <code>string status = 9;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 9;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string statusMessage = 10;</code>
   * @return The statusMessage.
   */
  java.lang.String getStatusMessage();
  /**
   * <code>string statusMessage = 10;</code>
   * @return The bytes for statusMessage.
   */
  com.google.protobuf.ByteString
      getStatusMessageBytes();
}
