// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geo-me.proto

package au.com.ausstaker.snet.server;

public final class GeoMe {
  private GeoMe() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GeoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GeoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Target_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Target_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Observation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Observation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GeolocationResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GeolocationResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014geo-me.proto\"a\n\nGeoRequest\022!\n\013observat" +
      "ion\030\001 \003(\0132\014.Observation\022\027\n\006target\030\002 \001(\0132" +
      "\007.Target\022\027\n\017provide_kml_out\030\003 \001(\010\"F\n\006Tar" +
      "get\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\020\n\010true_la" +
      "t\030\003 \001(\001\022\020\n\010true_lon\030\004 \001(\001\"v\n\013Observation" +
      "\022\n\n\002id\030\001 \001(\003\022\017\n\007assetId\030\002 \001(\t\022\013\n\003lat\030\003 \001" +
      "(\001\022\013\n\003lon\030\004 \001(\001\022\t\n\001x\030\005 \001(\001\022\t\n\001y\030\006 \001(\001\022\014\n" +
      "\004meas\030\007 \001(\001\022\014\n\004type\030\010 \001(\t\"\305\001\n\021Geolocatio" +
      "nResult\022\020\n\010residual\030\001 \001(\001\022\023\n\013residual_rk" +
      "\030\002 \001(\001\022\013\n\003lat\030\003 \001(\001\022\013\n\003lon\030\004 \001(\001\022\020\n\010elp_" +
      "long\030\005 \001(\001\022\021\n\telp_short\030\006 \001(\001\022\017\n\007elp_rot" +
      "\030\007 \001(\001\022\022\n\nkml_output\030\010 \001(\t\022\016\n\006status\030\t \001" +
      "(\t\022\025\n\rstatusMessage\030\n \001(\t2B\n\021ServiceDefi" +
      "nition\022-\n\010geoFixMe\022\013.GeoRequest\032\022.Geoloc" +
      "ationResult\"\000B#\n\034au.com.ausstaker.snet.s" +
      "erverP\001\210\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GeoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GeoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GeoRequest_descriptor,
        new java.lang.String[] { "Observation", "Target", "ProvideKmlOut", });
    internal_static_Target_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Target_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Target_descriptor,
        new java.lang.String[] { "Id", "Name", "TrueLat", "TrueLon", });
    internal_static_Observation_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Observation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Observation_descriptor,
        new java.lang.String[] { "Id", "AssetId", "Lat", "Lon", "X", "Y", "Meas", "Type", });
    internal_static_GeolocationResult_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GeolocationResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GeolocationResult_descriptor,
        new java.lang.String[] { "Residual", "ResidualRk", "Lat", "Lon", "ElpLong", "ElpShort", "ElpRot", "KmlOutput", "Status", "StatusMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
