// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geo-me.proto

package au.com.ausstaker.snet.server;

/**
 * Protobuf type {@code GeoRequest}
 */
public final class GeoRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GeoRequest)
    GeoRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GeoRequest.newBuilder() to construct.
  private GeoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GeoRequest() {
    observation_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GeoRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GeoRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              observation_ = new java.util.ArrayList<au.com.ausstaker.snet.server.Observation>();
              mutable_bitField0_ |= 0x00000001;
            }
            observation_.add(
                input.readMessage(au.com.ausstaker.snet.server.Observation.parser(), extensionRegistry));
            break;
          }
          case 18: {
            au.com.ausstaker.snet.server.Target.Builder subBuilder = null;
            if (target_ != null) {
              subBuilder = target_.toBuilder();
            }
            target_ = input.readMessage(au.com.ausstaker.snet.server.Target.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(target_);
              target_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {

            provideKmlOut_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        observation_ = java.util.Collections.unmodifiableList(observation_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return au.com.ausstaker.snet.server.GeoMe.internal_static_GeoRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return au.com.ausstaker.snet.server.GeoMe.internal_static_GeoRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            au.com.ausstaker.snet.server.GeoRequest.class, au.com.ausstaker.snet.server.GeoRequest.Builder.class);
  }

  public static final int OBSERVATION_FIELD_NUMBER = 1;
  private java.util.List<au.com.ausstaker.snet.server.Observation> observation_;
  /**
   * <code>repeated .Observation observation = 1;</code>
   */
  @java.lang.Override
  public java.util.List<au.com.ausstaker.snet.server.Observation> getObservationList() {
    return observation_;
  }
  /**
   * <code>repeated .Observation observation = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends au.com.ausstaker.snet.server.ObservationOrBuilder> 
      getObservationOrBuilderList() {
    return observation_;
  }
  /**
   * <code>repeated .Observation observation = 1;</code>
   */
  @java.lang.Override
  public int getObservationCount() {
    return observation_.size();
  }
  /**
   * <code>repeated .Observation observation = 1;</code>
   */
  @java.lang.Override
  public au.com.ausstaker.snet.server.Observation getObservation(int index) {
    return observation_.get(index);
  }
  /**
   * <code>repeated .Observation observation = 1;</code>
   */
  @java.lang.Override
  public au.com.ausstaker.snet.server.ObservationOrBuilder getObservationOrBuilder(
      int index) {
    return observation_.get(index);
  }

  public static final int TARGET_FIELD_NUMBER = 2;
  private au.com.ausstaker.snet.server.Target target_;
  /**
   * <code>.Target target = 2;</code>
   * @return Whether the target field is set.
   */
  @java.lang.Override
  public boolean hasTarget() {
    return target_ != null;
  }
  /**
   * <code>.Target target = 2;</code>
   * @return The target.
   */
  @java.lang.Override
  public au.com.ausstaker.snet.server.Target getTarget() {
    return target_ == null ? au.com.ausstaker.snet.server.Target.getDefaultInstance() : target_;
  }
  /**
   * <code>.Target target = 2;</code>
   */
  @java.lang.Override
  public au.com.ausstaker.snet.server.TargetOrBuilder getTargetOrBuilder() {
    return getTarget();
  }

  public static final int PROVIDE_KML_OUT_FIELD_NUMBER = 3;
  private boolean provideKmlOut_;
  /**
   * <code>bool provide_kml_out = 3;</code>
   * @return The provideKmlOut.
   */
  @java.lang.Override
  public boolean getProvideKmlOut() {
    return provideKmlOut_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < observation_.size(); i++) {
      output.writeMessage(1, observation_.get(i));
    }
    if (target_ != null) {
      output.writeMessage(2, getTarget());
    }
    if (provideKmlOut_ != false) {
      output.writeBool(3, provideKmlOut_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < observation_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, observation_.get(i));
    }
    if (target_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTarget());
    }
    if (provideKmlOut_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, provideKmlOut_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof au.com.ausstaker.snet.server.GeoRequest)) {
      return super.equals(obj);
    }
    au.com.ausstaker.snet.server.GeoRequest other = (au.com.ausstaker.snet.server.GeoRequest) obj;

    if (!getObservationList()
        .equals(other.getObservationList())) return false;
    if (hasTarget() != other.hasTarget()) return false;
    if (hasTarget()) {
      if (!getTarget()
          .equals(other.getTarget())) return false;
    }
    if (getProvideKmlOut()
        != other.getProvideKmlOut()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getObservationCount() > 0) {
      hash = (37 * hash) + OBSERVATION_FIELD_NUMBER;
      hash = (53 * hash) + getObservationList().hashCode();
    }
    if (hasTarget()) {
      hash = (37 * hash) + TARGET_FIELD_NUMBER;
      hash = (53 * hash) + getTarget().hashCode();
    }
    hash = (37 * hash) + PROVIDE_KML_OUT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getProvideKmlOut());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static au.com.ausstaker.snet.server.GeoRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static au.com.ausstaker.snet.server.GeoRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static au.com.ausstaker.snet.server.GeoRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static au.com.ausstaker.snet.server.GeoRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static au.com.ausstaker.snet.server.GeoRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static au.com.ausstaker.snet.server.GeoRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static au.com.ausstaker.snet.server.GeoRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static au.com.ausstaker.snet.server.GeoRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static au.com.ausstaker.snet.server.GeoRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static au.com.ausstaker.snet.server.GeoRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static au.com.ausstaker.snet.server.GeoRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static au.com.ausstaker.snet.server.GeoRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(au.com.ausstaker.snet.server.GeoRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GeoRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GeoRequest)
      au.com.ausstaker.snet.server.GeoRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return au.com.ausstaker.snet.server.GeoMe.internal_static_GeoRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return au.com.ausstaker.snet.server.GeoMe.internal_static_GeoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              au.com.ausstaker.snet.server.GeoRequest.class, au.com.ausstaker.snet.server.GeoRequest.Builder.class);
    }

    // Construct using au.com.ausstaker.snet.server.GeoRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getObservationFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (observationBuilder_ == null) {
        observation_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        observationBuilder_.clear();
      }
      if (targetBuilder_ == null) {
        target_ = null;
      } else {
        target_ = null;
        targetBuilder_ = null;
      }
      provideKmlOut_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return au.com.ausstaker.snet.server.GeoMe.internal_static_GeoRequest_descriptor;
    }

    @java.lang.Override
    public au.com.ausstaker.snet.server.GeoRequest getDefaultInstanceForType() {
      return au.com.ausstaker.snet.server.GeoRequest.getDefaultInstance();
    }

    @java.lang.Override
    public au.com.ausstaker.snet.server.GeoRequest build() {
      au.com.ausstaker.snet.server.GeoRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public au.com.ausstaker.snet.server.GeoRequest buildPartial() {
      au.com.ausstaker.snet.server.GeoRequest result = new au.com.ausstaker.snet.server.GeoRequest(this);
      int from_bitField0_ = bitField0_;
      if (observationBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          observation_ = java.util.Collections.unmodifiableList(observation_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.observation_ = observation_;
      } else {
        result.observation_ = observationBuilder_.build();
      }
      if (targetBuilder_ == null) {
        result.target_ = target_;
      } else {
        result.target_ = targetBuilder_.build();
      }
      result.provideKmlOut_ = provideKmlOut_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof au.com.ausstaker.snet.server.GeoRequest) {
        return mergeFrom((au.com.ausstaker.snet.server.GeoRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(au.com.ausstaker.snet.server.GeoRequest other) {
      if (other == au.com.ausstaker.snet.server.GeoRequest.getDefaultInstance()) return this;
      if (observationBuilder_ == null) {
        if (!other.observation_.isEmpty()) {
          if (observation_.isEmpty()) {
            observation_ = other.observation_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureObservationIsMutable();
            observation_.addAll(other.observation_);
          }
          onChanged();
        }
      } else {
        if (!other.observation_.isEmpty()) {
          if (observationBuilder_.isEmpty()) {
            observationBuilder_.dispose();
            observationBuilder_ = null;
            observation_ = other.observation_;
            bitField0_ = (bitField0_ & ~0x00000001);
            observationBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getObservationFieldBuilder() : null;
          } else {
            observationBuilder_.addAllMessages(other.observation_);
          }
        }
      }
      if (other.hasTarget()) {
        mergeTarget(other.getTarget());
      }
      if (other.getProvideKmlOut() != false) {
        setProvideKmlOut(other.getProvideKmlOut());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      au.com.ausstaker.snet.server.GeoRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (au.com.ausstaker.snet.server.GeoRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<au.com.ausstaker.snet.server.Observation> observation_ =
      java.util.Collections.emptyList();
    private void ensureObservationIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        observation_ = new java.util.ArrayList<au.com.ausstaker.snet.server.Observation>(observation_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        au.com.ausstaker.snet.server.Observation, au.com.ausstaker.snet.server.Observation.Builder, au.com.ausstaker.snet.server.ObservationOrBuilder> observationBuilder_;

    /**
     * <code>repeated .Observation observation = 1;</code>
     */
    public java.util.List<au.com.ausstaker.snet.server.Observation> getObservationList() {
      if (observationBuilder_ == null) {
        return java.util.Collections.unmodifiableList(observation_);
      } else {
        return observationBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Observation observation = 1;</code>
     */
    public int getObservationCount() {
      if (observationBuilder_ == null) {
        return observation_.size();
      } else {
        return observationBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Observation observation = 1;</code>
     */
    public au.com.ausstaker.snet.server.Observation getObservation(int index) {
      if (observationBuilder_ == null) {
        return observation_.get(index);
      } else {
        return observationBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Observation observation = 1;</code>
     */
    public Builder setObservation(
        int index, au.com.ausstaker.snet.server.Observation value) {
      if (observationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureObservationIsMutable();
        observation_.set(index, value);
        onChanged();
      } else {
        observationBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Observation observation = 1;</code>
     */
    public Builder setObservation(
        int index, au.com.ausstaker.snet.server.Observation.Builder builderForValue) {
      if (observationBuilder_ == null) {
        ensureObservationIsMutable();
        observation_.set(index, builderForValue.build());
        onChanged();
      } else {
        observationBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Observation observation = 1;</code>
     */
    public Builder addObservation(au.com.ausstaker.snet.server.Observation value) {
      if (observationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureObservationIsMutable();
        observation_.add(value);
        onChanged();
      } else {
        observationBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Observation observation = 1;</code>
     */
    public Builder addObservation(
        int index, au.com.ausstaker.snet.server.Observation value) {
      if (observationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureObservationIsMutable();
        observation_.add(index, value);
        onChanged();
      } else {
        observationBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Observation observation = 1;</code>
     */
    public Builder addObservation(
        au.com.ausstaker.snet.server.Observation.Builder builderForValue) {
      if (observationBuilder_ == null) {
        ensureObservationIsMutable();
        observation_.add(builderForValue.build());
        onChanged();
      } else {
        observationBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Observation observation = 1;</code>
     */
    public Builder addObservation(
        int index, au.com.ausstaker.snet.server.Observation.Builder builderForValue) {
      if (observationBuilder_ == null) {
        ensureObservationIsMutable();
        observation_.add(index, builderForValue.build());
        onChanged();
      } else {
        observationBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Observation observation = 1;</code>
     */
    public Builder addAllObservation(
        java.lang.Iterable<? extends au.com.ausstaker.snet.server.Observation> values) {
      if (observationBuilder_ == null) {
        ensureObservationIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, observation_);
        onChanged();
      } else {
        observationBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Observation observation = 1;</code>
     */
    public Builder clearObservation() {
      if (observationBuilder_ == null) {
        observation_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        observationBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Observation observation = 1;</code>
     */
    public Builder removeObservation(int index) {
      if (observationBuilder_ == null) {
        ensureObservationIsMutable();
        observation_.remove(index);
        onChanged();
      } else {
        observationBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Observation observation = 1;</code>
     */
    public au.com.ausstaker.snet.server.Observation.Builder getObservationBuilder(
        int index) {
      return getObservationFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Observation observation = 1;</code>
     */
    public au.com.ausstaker.snet.server.ObservationOrBuilder getObservationOrBuilder(
        int index) {
      if (observationBuilder_ == null) {
        return observation_.get(index);  } else {
        return observationBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Observation observation = 1;</code>
     */
    public java.util.List<? extends au.com.ausstaker.snet.server.ObservationOrBuilder> 
         getObservationOrBuilderList() {
      if (observationBuilder_ != null) {
        return observationBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(observation_);
      }
    }
    /**
     * <code>repeated .Observation observation = 1;</code>
     */
    public au.com.ausstaker.snet.server.Observation.Builder addObservationBuilder() {
      return getObservationFieldBuilder().addBuilder(
          au.com.ausstaker.snet.server.Observation.getDefaultInstance());
    }
    /**
     * <code>repeated .Observation observation = 1;</code>
     */
    public au.com.ausstaker.snet.server.Observation.Builder addObservationBuilder(
        int index) {
      return getObservationFieldBuilder().addBuilder(
          index, au.com.ausstaker.snet.server.Observation.getDefaultInstance());
    }
    /**
     * <code>repeated .Observation observation = 1;</code>
     */
    public java.util.List<au.com.ausstaker.snet.server.Observation.Builder> 
         getObservationBuilderList() {
      return getObservationFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        au.com.ausstaker.snet.server.Observation, au.com.ausstaker.snet.server.Observation.Builder, au.com.ausstaker.snet.server.ObservationOrBuilder> 
        getObservationFieldBuilder() {
      if (observationBuilder_ == null) {
        observationBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            au.com.ausstaker.snet.server.Observation, au.com.ausstaker.snet.server.Observation.Builder, au.com.ausstaker.snet.server.ObservationOrBuilder>(
                observation_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        observation_ = null;
      }
      return observationBuilder_;
    }

    private au.com.ausstaker.snet.server.Target target_;
    private com.google.protobuf.SingleFieldBuilderV3<
        au.com.ausstaker.snet.server.Target, au.com.ausstaker.snet.server.Target.Builder, au.com.ausstaker.snet.server.TargetOrBuilder> targetBuilder_;
    /**
     * <code>.Target target = 2;</code>
     * @return Whether the target field is set.
     */
    public boolean hasTarget() {
      return targetBuilder_ != null || target_ != null;
    }
    /**
     * <code>.Target target = 2;</code>
     * @return The target.
     */
    public au.com.ausstaker.snet.server.Target getTarget() {
      if (targetBuilder_ == null) {
        return target_ == null ? au.com.ausstaker.snet.server.Target.getDefaultInstance() : target_;
      } else {
        return targetBuilder_.getMessage();
      }
    }
    /**
     * <code>.Target target = 2;</code>
     */
    public Builder setTarget(au.com.ausstaker.snet.server.Target value) {
      if (targetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        target_ = value;
        onChanged();
      } else {
        targetBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Target target = 2;</code>
     */
    public Builder setTarget(
        au.com.ausstaker.snet.server.Target.Builder builderForValue) {
      if (targetBuilder_ == null) {
        target_ = builderForValue.build();
        onChanged();
      } else {
        targetBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Target target = 2;</code>
     */
    public Builder mergeTarget(au.com.ausstaker.snet.server.Target value) {
      if (targetBuilder_ == null) {
        if (target_ != null) {
          target_ =
            au.com.ausstaker.snet.server.Target.newBuilder(target_).mergeFrom(value).buildPartial();
        } else {
          target_ = value;
        }
        onChanged();
      } else {
        targetBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Target target = 2;</code>
     */
    public Builder clearTarget() {
      if (targetBuilder_ == null) {
        target_ = null;
        onChanged();
      } else {
        target_ = null;
        targetBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Target target = 2;</code>
     */
    public au.com.ausstaker.snet.server.Target.Builder getTargetBuilder() {
      
      onChanged();
      return getTargetFieldBuilder().getBuilder();
    }
    /**
     * <code>.Target target = 2;</code>
     */
    public au.com.ausstaker.snet.server.TargetOrBuilder getTargetOrBuilder() {
      if (targetBuilder_ != null) {
        return targetBuilder_.getMessageOrBuilder();
      } else {
        return target_ == null ?
            au.com.ausstaker.snet.server.Target.getDefaultInstance() : target_;
      }
    }
    /**
     * <code>.Target target = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        au.com.ausstaker.snet.server.Target, au.com.ausstaker.snet.server.Target.Builder, au.com.ausstaker.snet.server.TargetOrBuilder> 
        getTargetFieldBuilder() {
      if (targetBuilder_ == null) {
        targetBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            au.com.ausstaker.snet.server.Target, au.com.ausstaker.snet.server.Target.Builder, au.com.ausstaker.snet.server.TargetOrBuilder>(
                getTarget(),
                getParentForChildren(),
                isClean());
        target_ = null;
      }
      return targetBuilder_;
    }

    private boolean provideKmlOut_ ;
    /**
     * <code>bool provide_kml_out = 3;</code>
     * @return The provideKmlOut.
     */
    @java.lang.Override
    public boolean getProvideKmlOut() {
      return provideKmlOut_;
    }
    /**
     * <code>bool provide_kml_out = 3;</code>
     * @param value The provideKmlOut to set.
     * @return This builder for chaining.
     */
    public Builder setProvideKmlOut(boolean value) {
      
      provideKmlOut_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool provide_kml_out = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearProvideKmlOut() {
      
      provideKmlOut_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GeoRequest)
  }

  // @@protoc_insertion_point(class_scope:GeoRequest)
  private static final au.com.ausstaker.snet.server.GeoRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new au.com.ausstaker.snet.server.GeoRequest();
  }

  public static au.com.ausstaker.snet.server.GeoRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GeoRequest>
      PARSER = new com.google.protobuf.AbstractParser<GeoRequest>() {
    @java.lang.Override
    public GeoRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GeoRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GeoRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GeoRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public au.com.ausstaker.snet.server.GeoRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

